/**
 * The export bundle: everything a person needs to take the generated tools away.
 *
 * A code viewer in a web page is a demo. A zip you can open in your editor is a
 * deliverable, and this project's whole claim is that the output is real code rather
 * than a preview of code.
 *
 * What goes in, and why each of it:
 *
 *   README.md      what the files are, how to install them, and what is still on you
 *   CONSENT.md     who decided what, per tool. The reviewable record of the one
 *                  decision the generator refuses to make on anyone's behalf
 *   manifest.json  the same thing machine-readable, for anyone diffing bundles
 *   tools/*.ts     imperative modules, ready to import
 *   tools/*.html   annotated markup, ready to paste over the original form
 */

import { createZip } from "./zip";
import type { GeneratedTool } from "./generate";
import type { ZipEntry } from "./zip";

export interface BundleInput {
  tools: readonly GeneratedTool[];
  /** Fixed by the caller, so the same tools produce the same bytes. */
  generatedAt: Date;
}

const CHECKPOINT_PROSE: Record<string, string> = {
  "person-submits": "A person presses the button. The browser fills the form and waits.",
  "person-approves": "A person approves a prompt. The agent submits; nothing is written until someone says yes.",
  "none-needed": "Nobody checks. Allowed only because this tool changes nothing.",
};

function readme(tools: readonly GeneratedTool[], generatedAt: Date): string {
  const rows = tools
    .map(
      (entry) =>
        `| \`${entry.proposal.name}\` | ${entry.proposal.route} | \`tools/${fileNameFor(entry)}\` |`,
    )
    .join("\n");

  return `# WebMCP tools for your site

Generated by Toolsmith on ${generatedAt.toISOString().slice(0, 10)}. Every tool in here was
reviewed and approved by a person before it was written out.

| Tool | Route | File |
|---|---|---|
${rows}

## Installing them

**Imperative tools** (\`.ts\`) are standalone modules with no imports and no framework.
Drop one into your project, call its \`register…\` function once the page is ready, and
call the function it returns when the UI that tool acts on goes away:

\`\`\`ts
const unregister = registerYourTool();
// later, when that part of the page is gone:
unregister();
\`\`\`

They feature-detect \`document.modelContext\`, so on a browser without WebMCP they do
nothing at all and your page behaves exactly as it did.

**Declarative tools** (\`.html\`) are your own form with tool attributes added. Replace
your form's markup with the version here, or copy the \`toolname\`,
\`tooldescription\`, and \`toolparamdescription\` attributes across by hand. The browser
builds the tool from the markup; there is no JavaScript to add.

## What is still on you

Each imperative module has one \`TODO\` in it, where the action itself goes. Three rules
for what you write there, none of them optional:

1. **Validate the arguments again, on the server.** The schema in the tool is advice to
   the agent, not a guarantee. Nothing stops a caller ignoring it.
2. **Return nothing internal.** No database IDs, no URLs that grant access, no upstream
   error text. Say what happened in your own words.
3. **Be honest about ambiguity.** If you cannot tell whether the action took effect, say
   so and say it is unsafe to retry. Never guess.

## What is not in here

The consent gate and the receipt ledger. Those are app-level features, because the
platform has not settled consent yet (webmcp issues #165, #176). Each mutating tool has
a \`requestApproval\` stub that returns \`false\` until you write it, so an unfinished
integration refuses to act rather than acting unattended. Read \`CONSENT.md\` before you
change that.
`;
}

function consentDoc(tools: readonly GeneratedTool[]): string {
  const sections = tools
    .map((entry) => {
      const { proposal } = entry;
      const mutating = proposal.annotations.readOnlyHint !== true;
      const decided = proposal.consent.answered
        ? CHECKPOINT_PROSE[proposal.consent.choice]
        : "Not answered. The cautious default applies: a person presses the button, and no `toolautosubmit` was written.";

      return `## \`${proposal.name}\`

- Changes data: ${mutating ? "yes" : "no"}
- Question asked: ${proposal.consent.question}
- Answer: ${decided}
- \`toolautosubmit\` written: ${
        proposal.route === "declarative" && entry.declarative?.html.includes("toolautosubmit")
          ? "yes"
          : "no"
      }`;
    })
    .join("\n\n");

  return `# Consent decisions

\`toolautosubmit\` is not a convenience setting. Without it the browser fills a form and
waits for a person; with it the agent submits and nobody is standing there. It is the
consent decision for a declarative tool, which is why Toolsmith asks it as a question
with named answers rather than offering a checkbox.

A tool that changes data is never offered the unattended option. That is not a policy
this generator invented; it is the floor.

${sections}
`;
}

function manifest(tools: readonly GeneratedTool[], generatedAt: Date): string {
  return JSON.stringify(
    {
      generator: "toolsmith",
      generatedAt: generatedAt.toISOString(),
      tools: tools.map((entry) => ({
        name: entry.proposal.name,
        title: entry.proposal.title,
        route: entry.proposal.route,
        readOnly: entry.proposal.annotations.readOnlyHint === true,
        consent: {
          answered: entry.proposal.consent.answered,
          checkpoint: entry.proposal.consent.choice,
        },
        parameters: entry.proposal.params.map((param) => ({
          name: param.name,
          required: param.required,
        })),
        file: `tools/${fileNameFor(entry)}`,
      })),
    },
    null,
    2,
  );
}

function fileNameFor(entry: GeneratedTool): string {
  return `${entry.proposal.name}.${entry.proposal.route === "declarative" ? "html" : "ts"}`;
}

/** The files that go in the archive, in a stable order. */
export function bundleFiles({ tools, generatedAt }: BundleInput): ZipEntry[] {
  const entries: ZipEntry[] = [
    { path: "README.md", content: readme(tools, generatedAt) },
    { path: "CONSENT.md", content: consentDoc(tools) },
    { path: "manifest.json", content: manifest(tools, generatedAt) },
  ];

  for (const tool of tools) {
    const content =
      tool.proposal.route === "declarative"
        ? (tool.declarative?.html ?? "")
        : (tool.imperative?.code ?? "");

    // A tool that emitted nothing is skipped rather than shipped empty: a zero-byte
    // module in a bundle reads as a bug in the site, not as a refusal here. A blocked
    // one is skipped too, in case it reached here by a path the UI does not guard.
    if (content.trim().length === 0 || tool.proposal.blockers.length > 0) continue;

    entries.push({ path: `tools/${fileNameFor(tool)}`, content });
  }

  return entries;
}

/** The archive itself. */
export function buildBundle(input: BundleInput): Uint8Array {
  return createZip(bundleFiles(input), input.generatedAt);
}

/** A filename for the download, stamped so successive exports do not overwrite. */
export function bundleFileName(generatedAt: Date): string {
  return `toolsmith-tools-${generatedAt.toISOString().slice(0, 19).replace(/[:T]/g, "-")}.zip`;
}
